# Generated by Django 2.0.6 on 2018-07-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.CharField(default='/static/default.gif', max_length=128),
        ),
    ]
