# Generated by Django 2.0.6 on 2018-07-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20180721_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.CharField(default='/static/img/default.gif', max_length=128),
        ),
    ]
